name: PHP8.3

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@8.3
        with:
          dir: '.'
      - name: Run ESLint
        run: npm run lint
      - name: Install dependencies in resources
        run: cd resources && npm install
      - name: Start Daemon
        run: nohup npm start &
      - name: Wait for the server to be ready
        run: sleep 5
      - name: Verify server is running
        run: |
          curl --fail http://localhost:1555/stop || exit 1
